### PR TITLE
Added Randoli as a vendor in enterprise page

### PR DESCRIPTION
**Pull request by rajith77**
Added Randoli as an vendor in the enterprise page as suggested by Alex

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Hi @rajith77 -- could you share a little more about how Randoli is using Opencost , support model, as well as any PRs or issues the Randoli team has collaborated on?

**Comment by rajith77** [comment]
> Hi @rajith77 -- could you share a little more about how Randoli is using Opencost , support model, as well as any PRs or issues the Randoli team has collaborated on?

@AjayTripathy I didn't notice your response. My apologies.
- Our team has been attending meetings consistently for the last 4-5 months
- We have submitted a PR for getting OpenCost running on OpenShift
- We have responded to community user questions, raised issues and trying to work with Alex on LTS support
- I personally helped with the OpenCost project booth during KubeCon
- I have done 4-5 community talks in Toronto, UAE & India about OpenCost

Randoli App Insights platform provides Cost Management powered by OpenCost.
We provide enterprise support.

**Review by ameijer — APPROVED** [review]

**Review by cliffcolvin — APPROVED** [review]
LGTM, thanks for the contributions!

**Comment by rajith77** [comment]
Thank you!

**Pull request merged**
