### PR TITLE
Add Vantage to the Enterprise page

### PR DESCRIPTION
**Pull request by mattray**
vantage

### CODE REVIEW

**Comment by AjayTripathy** [comment]
There's a ton of technical validation we do with partner solutions before we consider something like this. Closing for now but feel free to reach out with further thoughts on partnership.

**Comment by EverettBerry** [comment]
Hi Ajay!

Good to be connected. I got the following from Matt - who originally invited us to participate here as part of the CNCF Incubation effort:

> “My apologies for the PR being closed. I did not know there was technical validation required for OpenCost projects, I assumed it was simply marketing-based. Let me figure out what the next steps are and I'll get back to you.”

I’m looping in @brookemckim, Vantage Co-Founder & CTO, to see what we can do to do technical validation here to support you all. Do you mind sharing what the technical validation steps are and we’re happy to complete them? 

To the best of our knowledge, there isn’t anything fancy happening here. We are simply having customers deploy OpenCost and having a remote-write to a prometheus endpoint which Vantage integrates with. Let us know how we can best support OpenCost - we’ve got a track record of trying to be supportive with it on our [official blog](https://www.vantage.sh/blog/vantage-launches-opencost-kubernetes-monitoring-support), the [CNCF announcement](https://www.cncf.io/blog/2022/12/06/opencost-a-new-cncf-sandbox-project-for-real-time-kubernetes-cost-monitoring/) and by recommending OpenCost as the preferred way to do Kubernetes cost monitoring in our [docs](https://docs.vantage.sh/opencost). 

Let us know and we’re happy to help here.

**Comment by EverettBerry** [comment]
@AjayTripathy bumping for visibility. Happy to talk through technical validation or what might be needed next.

**Comment by AjayTripathy** [comment]
Thanks for following up here and sorry for the late response, we've been busy with kubecon prep. The plan is for us to label solutions that export metrics for display like Vantage, and Grafana as supported "integrations." These will need limited validation. Enterprise solutions should support application lifecycle including deployment, upgrade, monitoring, and support SLAs for the platform. The intention is to add another page listing integrations with linkbacks to integration setup.

**Pull request closed without merging**
