### PR TITLE
Enterprise landing page

### PR DESCRIPTION
**Pull request by mattray**
New Enterprise tab and landing page. Styled after https://www.figma.com/file/I8XMe7wkMiDzL27U8ISypU/OpenCost-Enterprise?node-id=27%3A140&t=IOSD0BzBGb4Q5PzH-0

Fixes https://github.com/opencost/opencost-website/issues/66

Screen Shot 2022-12-14 at 1 46 18 AM

### CODE REVIEW

**Comment by dwbrown2** [comment]
+1 on @Annalillie's comments! I feel drop shadows really help group content in these cards

**Comment by Annalillie** [comment]
Burke has volunteered to help out here. His name isn't popping up for a mention but I have sent him this issue and its details.

**Comment by mattray** [comment]
@Annalillie I appreciate how the 2 things you mentioned are the exact 2 that I fought with before giving up 🤣

**Comment by mattray** [comment]
I've given Burke a screenshot with the needed changes highlighted

**Comment by burkeshartsis** [comment]
Alright, I think this is about as far as I can take this right now. I've fixed and/or improved what I could where I could. @mattray just let me know if there is anything else I can help with. Happy to walk through my changes with you in detail and to continue to be involved where ever. Below is a long-ish overview (watch at 1.5-2x) of where things landed. Enjoy!

[](https://www.loom.com/share/f6a3f61c10a646cbb884b238c7719adb)

**Pull request merged**
