### PR TITLE
Fix of Large gap under the hero section on opencost.io #5

### LINKED ISSUE #5: Large gap under the hero section on opencost.io
There is a large gap between the hero section and the Cost allocation, simple & standard title. 

Screen Shot 2022-06-03 at 3 24 21 PM

### PR DESCRIPTION
**Pull request by iswarmondal**
closes #5

### CODE REVIEW

**Comment by AdamStack18** [comment]
@elenalape, Would you have time today or tomorrow to review this PR?

**Review by elenalape — DISMISSED** [review]
hi @iswarmondal, thank you for a speedy PR! ✨  as i mentioned in #5, please can we make sure that the Hero spans the entire screen? the Feature section should only be revealed as you scroll down, and setting a `min-h` or `max-h` on the entire component doesn't guarantee that:

Screenshot 2022-06-15 at 19 04 06

if the gap feels on larger screens, we can instead tweak the size of the content, i.e. text and image. let me know if you need any help there.

**Comment by iswarmondal** [comment]
Sure!
@elenalape take a look and let me know if any further edits needed

**Review by srpomeroy — APPROVED** [review]
Deployment LGTM based on the guidelines @elenalape laid out.

**Comment by srpomeroy** [comment]
Good to go here @iswarmondal thanks for contributing! You may merge when ready.

**Comment by Adam-Stack-PM** [comment]
@teevans @elenalape and @iswarmondal,  Do we still want to merge this PR?  I'm not 100% sure as my original issue did not take into account the design intent.   A possible solution would be to reveal on scroll.

**Comment by iswarmondal** [comment]
> @teevans @elenalape and @iswarmondal, Do we still want to merge this PR? I'm not 100% sure as my original issue did not take into account the design intent. A possible solution would be to reveal on scroll.

Should I implement the reveal on scroll? Some libraries can be very handy. Tell me you thoughts @Adam-Stack-PM

**Comment by Adam-Stack-PM** [comment]
@iswarmondal, thanks for the follow up.  @elenalape, Would love your input on the above when you have time before we move forward.

**Comment by Adam-Stack-PM** [comment]
@iswarmondal, After talking to the team would go a head and proceed with the change to reveal on scroll.

**Comment by iswarmondal** [comment]
Sure @Adam-Stack-PM , I will update my pr accordingly. Is it ok if I use some library for that?

**Comment by Adam-Stack-PM** [comment]
Lets run that by one of our engineers. @nikovacevic, @teevans or @AjayTripathy, see above.

**Review by mattray — APPROVED** [review]

**Comment by mattray** [comment]
I deployed this and took screenshots for comparison.
before
after

**Comment by mattray** [comment]
@iswarmondal Thanks!

**Pull request merged**
