### PR TITLE
Initial outline of available API calls.

### PR DESCRIPTION
**Pull request by mattray**
We will continue to revise and expand the API documentation coverage, this is intended as a work-in-progress.

Signed-off-by: Matt Ray <github@mattray.dev>

### CODE REVIEW

**Comment by mattray** [comment]
I believe it's worth publishing as-is to provide initial guidance. It's probably worth breaking this up into individual pages for each API endpoint, with example queries and output.

**Comment by mattray** [comment]
@AjayTripathy @bstuder99 @dwbrown2 @jessegoodier I'd appreciate feedback on organizational thoughts on the API docs. What would you like to see, how it should be segmented, etc. An OpenAPI-based refactoring will be extensive and potentially time-consuming, but it would open up automatic generation of documentation and SDKs.

**Comment by bstuder99** [comment]
Great idea. I'm going to be working on overhauling our Kubecost API docs as well in January using GitBook's integrated API doc templates. For OpenCost we may not have the best visual presentation of this content if we choose to use raw Markdown.

**Comment by mattray** [comment]
@bstuder99 absolutely agree on not using Markdown. Once it's in a machine-processible format via OpenAPI we can move it to React or whatever.

**Comment by dwbrown2** [comment]
Thanks for sharing, Matt. How far is this / what would be outstanding for a OpenAPI-based implementation?

**Comment by bstuder99** [comment]
Dropping a comment in this thread in case this got buried in people's inboxes over the holidays. Would like to follow up on this the next week or so possible over call to work through the details.

**Comment by mattray** [comment]
Closing in favor of replacing with generated documentation.

**Pull request closed without merging**
